// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8-K4F-K7NW4IWuahSxhfle_WMaatH9o',
    appId: '1:553076360647:android:ff021f69b1ce2a07c345e2',
    messagingSenderId: '553076360647',
    projectId: 'all-test-project-1eddd',
    storageBucket: 'all-test-project-1eddd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWoO1Q-CjjPOXVaZSBsXKs98LO3Bjd3Tg',
    appId: '1:553076360647:ios:0110fcac83cf143ac345e2',
    messagingSenderId: '553076360647',
    projectId: 'all-test-project-1eddd',
    storageBucket: 'all-test-project-1eddd.appspot.com',
    iosClientId: '553076360647-u3k8fstj83009tkedo3qp02lmb0i1sld.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewNewStartUp',
  );
}
